#!/usr/bin/env bash

set -e

# Debug output
echo "Current directory: $(pwd)"
ls -la

# Change directory to the root of the Git repository
ROOTDIR="$(git rev-parse --show-toplevel)"
cd "$ROOTDIR"

# Debug output
echo "Root directory of Git repository: $ROOTDIR"
ls -la "$ROOTDIR"

# Generate AUTHORS file
cat > AUTHORS <<- EOF
    # File @generated by generate-authors.sh. DO NOT EDIT.
    # This file lists all contributors to the repository.
    # See generate-authors.sh to make modifications.

    $(git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
